// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// StatusSyncListerExpansion allows custom methods to be added to
// StatusSyncLister.
type StatusSyncListerExpansion interface{}

// StatusSyncNamespaceListerExpansion allows custom methods to be added to
// StatusSyncNamespaceLister.
type StatusSyncNamespaceListerExpansion interface{}
