// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1alpha1 "github.com/qiujian16/work-syncer/pkg/apis/v1alpha1"
	scheme "github.com/qiujian16/work-syncer/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// StatusSyncsGetter has a method to return a StatusSyncInterface.
// A group's client should implement this interface.
type StatusSyncsGetter interface {
	StatusSyncs(namespace string) StatusSyncInterface
}

// StatusSyncInterface has methods to work with StatusSync resources.
type StatusSyncInterface interface {
	Create(ctx context.Context, statusSync *v1alpha1.StatusSync, opts v1.CreateOptions) (*v1alpha1.StatusSync, error)
	Update(ctx context.Context, statusSync *v1alpha1.StatusSync, opts v1.UpdateOptions) (*v1alpha1.StatusSync, error)
	UpdateStatus(ctx context.Context, statusSync *v1alpha1.StatusSync, opts v1.UpdateOptions) (*v1alpha1.StatusSync, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.StatusSync, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.StatusSyncList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.StatusSync, err error)
	StatusSyncExpansion
}

// statusSyncs implements StatusSyncInterface
type statusSyncs struct {
	client rest.Interface
	ns     string
}

// newStatusSyncs returns a StatusSyncs
func newStatusSyncs(c *WorkV1alpha1Client, namespace string) *statusSyncs {
	return &statusSyncs{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the statusSync, and returns the corresponding statusSync object, and an error if there is any.
func (c *statusSyncs) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.StatusSync, err error) {
	result = &v1alpha1.StatusSync{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("statussyncs").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of StatusSyncs that match those selectors.
func (c *statusSyncs) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.StatusSyncList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.StatusSyncList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("statussyncs").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested statusSyncs.
func (c *statusSyncs) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("statussyncs").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a statusSync and creates it.  Returns the server's representation of the statusSync, and an error, if there is any.
func (c *statusSyncs) Create(ctx context.Context, statusSync *v1alpha1.StatusSync, opts v1.CreateOptions) (result *v1alpha1.StatusSync, err error) {
	result = &v1alpha1.StatusSync{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("statussyncs").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(statusSync).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a statusSync and updates it. Returns the server's representation of the statusSync, and an error, if there is any.
func (c *statusSyncs) Update(ctx context.Context, statusSync *v1alpha1.StatusSync, opts v1.UpdateOptions) (result *v1alpha1.StatusSync, err error) {
	result = &v1alpha1.StatusSync{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("statussyncs").
		Name(statusSync.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(statusSync).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *statusSyncs) UpdateStatus(ctx context.Context, statusSync *v1alpha1.StatusSync, opts v1.UpdateOptions) (result *v1alpha1.StatusSync, err error) {
	result = &v1alpha1.StatusSync{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("statussyncs").
		Name(statusSync.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(statusSync).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the statusSync and deletes it. Returns an error if one occurs.
func (c *statusSyncs) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("statussyncs").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *statusSyncs) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("statussyncs").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched statusSync.
func (c *statusSyncs) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.StatusSync, err error) {
	result = &v1alpha1.StatusSync{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("statussyncs").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
