// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/qiujian16/work-syncer/pkg/client/clientset/versioned/typed/apis/v1alpha1"
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
)

type FakeWorkV1alpha1 struct {
	*testing.Fake
}

func (c *FakeWorkV1alpha1) StatusSyncs(namespace string) v1alpha1.StatusSyncInterface {
	return &FakeStatusSyncs{c, namespace}
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeWorkV1alpha1) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
