// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	time "time"

	apisv1alpha1 "github.com/qiujian16/work-syncer/pkg/apis/v1alpha1"
	versioned "github.com/qiujian16/work-syncer/pkg/client/clientset/versioned"
	internalinterfaces "github.com/qiujian16/work-syncer/pkg/client/informers/externalversions/internalinterfaces"
	v1alpha1 "github.com/qiujian16/work-syncer/pkg/client/listers/apis/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// StatusSyncInformer provides access to a shared informer and lister for
// StatusSyncs.
type StatusSyncInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.StatusSyncLister
}

type statusSyncInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewStatusSyncInformer constructs a new informer for StatusSync type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewStatusSyncInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredStatusSyncInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredStatusSyncInformer constructs a new informer for StatusSync type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredStatusSyncInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.WorkV1alpha1().StatusSyncs(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.WorkV1alpha1().StatusSyncs(namespace).Watch(context.TODO(), options)
			},
		},
		&apisv1alpha1.StatusSync{},
		resyncPeriod,
		indexers,
	)
}

func (f *statusSyncInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredStatusSyncInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *statusSyncInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&apisv1alpha1.StatusSync{}, f.defaultInformer)
}

func (f *statusSyncInformer) Lister() v1alpha1.StatusSyncLister {
	return v1alpha1.NewStatusSyncLister(f.Informer().GetIndexer())
}
